version: "2"
linters:
  default: all
  disable:
    - varnamelen
    - tagalign
    - nlreturn
    - mnd
    - gochecknoglobals
    - funlen
    - exhaustruct
    - tagliatelle
    - depguard
    - contextcheck
    - ireturn
    - perfsprint
    - nosprintfhostport
  enable:
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - testpackage
    - unconvert
    - unparam
    - unused
    - wrapcheck
    - wsl
  settings:
    gocognit:
      min-complexity: 15
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 150
      tab-width: 1
    misspell:
      locale: UK
    nestif:
      min-complexity: 4
    nolintlint:
      require-explanation: true
      require-specific: true
    wsl:
      allow-cuddle-declarations: false
      force-err-cuddling: true
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    warn-unused: true
    rules:
      - linters:
          - lll
        source: '^//go:generate '
formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
