services:
    mqtt:
        image: eclipse-mosquitto:2.0.20
        restart: unless-stopped
        volumes:
            - './mqtt/mosquitto-data:/mosquitto'
            - './mqtt/custom.conf:/mqttconf/custom.conf'
            - './mqtt/mqttcreds.txt:/mqttconf/mqttcreds.txt'
        command: 'mosquitto -c /mqttconf/custom.conf'
        ports:
          - 1883:1883
