name: PR

on:
  pull_request:

jobs:
  runner-job:
    name: Build & Test
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.23.5
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Build
        run: go build -v .

      - name: Test
        run: |
          go test -v ./...

  golangci:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63.4
